### ISSUE TITLE
Blink.msg() not working with Blink.loadhtml()

### ISSUE THREAD

**Issue by lukasfischer83** [JuliaGizmos/Blink.jl#186]
```
using Blink

# Working:
w1 = Window(async=false)
handle(w1, "press") do arg
  println(arg)
end
body!(w1, """<html><head><title>Window1</title><body><button onclick='Blink.msg("press", "Window1")'>go</button></body></head></html>""", async=false);

# Not Working:
w2 = Window(async=false)
handle(w2, "press") do arg
  println(arg)
end
loadhtml(w2, """<html><head><title>Window2</title><body><button onclick='Blink.msg("press", "Window2")'>go</button></body></head></html>""");

```

Is this intentional? I am trying to load a big site (lots of JS variables for google maps overlay) which hangs when I pass it to body!(), while loadhtml() would work.
Thanks, Lukas

**Comment by srgk26** [comment]
I'm sorry, I can't answer your question. But I need help from you/anyone else who may be able to help pls. Not entirely related, but it's based on your code strucuture.

I am developing a GUI where I would get user input and use the input value to do something else. I found a way to do this with another method, but I'm now trying to use HTML/CSS as the main styling code and would need to communicate between javascript and julia.

This is a very simple code for a Blink window:

```
using Blink
w = Blink.Window()
Blink.body!(w, html"""<input id="test" placeholder="Enter text here"><button onclick='Blink.msg("press", "foo")'>Press me!</button>""")
Blink.handle(w, "press") do args...
    Blink.body!(w, @js_ w document.getElementById("test").value)
end
```
The page layout works (it shows the input text field and the click button). But when I click the button, it doesn't show the value of the text input. I know that the message passing works though since this works:

```
Blink.handle(w, "press") do args...
    Blink.body!(w, "This works!")
end
```
The problem therefore is accessing the input text value from within julia. I need to access this input text value from within Julia. Please, could anyone help?

**Comment by srgk26** [comment]
> ```
> using Blink
> 
> # Working:
> w1 = Window(async=false)
> handle(w1, "press") do arg
>   println(arg)
> end
> body!(w1, """<html><head><title>Window1</title><body><button onclick='Blink.msg("press", "Window1")'>go</button></body></head></html>""", async=false);
> 
> # Not Working:
> w2 = Window(async=false)
> handle(w2, "press") do arg
>   println(arg)
> end
> loadhtml(w2, """<html><head><title>Window2</title><body><button onclick='Blink.msg("press", "Window2")'>go</button></body></head></html>""");
> ```
> 
> 
> Is this intentional? I am trying to load a big site (lots of JS variables for google maps overlay) which hangs when I pass it to body!(), while loadhtml() would work.
> 
> Thanks, Lukas

Actually, I may be answer your question. This would do the trick, if this is what you're looking for (I know it's over 3 months though):

```
using Blink
w = Blink.Window()
page = open("file.html") do io; read(io, String); end
Blink.body!(w, page)
```

**Comment by travigd** [comment]
@srgk26 Please open a new issue if you'd like to ask your own question, we're happy to help. :^)

@lukasfischer83 `loadhtml` doesn't include the Blink JavaScript setup code (which defines the `Blink` global in the JS side and enables Julia/JS communication); we also can't really modify it to do so since we'd have to inject it into the `<head />` portion of your HTML.

`body!` shouldn't hang though - that might be a bug.
